projects/rails_crud/coffeeshop/config/routes.rb
Rails.application.routes.draw do
  
	get "beans/" => "beans#index"
	get "beans/new" => "beans#new", as: :new_bean
	get "beans/:id" => "beans#show", as: :bean
	post "beans/" => "beans#create"
	get "beans/:id/edit" => "beans#edit", as: :edit_bean
	patch "beans/:id" => "beans#update"
	delete "beans/:id" => "beans#destroy"

end

projects/rails_crud/coffeeshop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projects/rails_crud/coffeeshop/app/models/bean.rb
class Bean < ApplicationRecord
end

projects/rails_crud/coffeeshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

projects/rails_crud/coffeeshop/app/controllers/beans_controller.rb
class BeansController < ApplicationController

    before_action :set_bean, only: [:show, :edit, :update, :destroy]

    def index
        @beans = Bean.all
    end

    def show
        @bean = Bean.find(params[:id])
    end

    def new
        @bean = Bean.new
    end

    def create
        @bean = Bean.new(bean_params)
      
        if @bean.save
            redirect_to beans_path
        else
            render :new
        end
    end

    def edit
        @bean = Bean.find(params[:id])
    end

    def update
        @bean = Bean.find(params[:id])

        if @bean.update_attributes(bean_params)
            redirect_to beans_path
        else
            render :edit
        end
    end

    def destroy
        @bean = Bean.find(params[:id])
        @bean.destroy
        redirect_to beans_path
    end

    private

    def bean_params
        params.require(:bean).permit(:name, :roast, :origin, :quantity)
    end

    def set_bean
        @bean = Bean.find(params[:id])
    end

end

projects/rails_crud/coffeeshop/app/helpers/application_helper.rb
module ApplicationHelper
end

projects/rails_crud/coffeeshop/app/helpers/beans_helper.rb
module BeansHelper
end

projects/rails_crud/coffeeshop/app/views/beans/edit.html.erb
<h1>Edit this bean!</h1>

<%= form_for @bean do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :roast %>
        <%= f.text_field :roast %>
    </div>

    <div>
        <%= f.label :origin %>
        <%= f.text_field :origin %>
    </div>

    <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the list!", beans_path %>

projects/rails_crud/coffeeshop/app/views/beans/index.html.erb
<h1>Today's Beans</h1>

<ul>
    <% @beans.each do |bean| %>
        <li>
            <strong> <%= bean.name %> </strong> - <%= bean.roast %>
            <%= link_to "More info", bean_path(bean) %>
        </li>
    <% end %>
    <br>
    <%= link_to "Add a bean!", new_bean_path %>
</ul>

projects/rails_crud/coffeeshop/app/views/beans/new.html.erb
<%= form_for @bean do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :roast %>
        <%= f.text_field :roast %>
    </div>

    <div>
        <%= f.label :origin %>
        <%= f.text_field :origin %>
    </div>

    <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Add new bean!" %>

<% end %>

<%= link_to "Back to the list!", beans_path %>

projects/rails_crud/coffeeshop/app/views/beans/show.html.erb
<h1><%= @bean.name %></h1>

<p>This coffee is a <%= @bean.roast %> roast from <%= @bean.origin %>, and we have <%= @bean.quantity %> pounds available.</p>

<%= link_to "Edit this bean!", edit_bean_path(@bean) %>
<%= link_to "Delete this bean!", :bean, method: :delete, data: { confirm: "Are you sure you want to delete this bean?"} %>
<%= link_to "Back to the list!", beans_path %>

projects/rails_crud/coffeeshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeeshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>